
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  profiles:
    active: dev
logging:
  level:
    root: info
    cn:
      wildfirechat:
        app: debug
        sdk: debug
