
spring:
  jpa:
    show-sql: true
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui
    enabled: true
logging:
  level:
    root: info
    cn:
      wildfirechat:
        app: debug
        sdk: debug
